services:
  mongodb:
    image: mongo:6.0
    container_name: emotion_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web-app:
    build: ./web_app            
    ports:
      - "5050:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/emotiondb
      - UPLOAD_DIR=/data/uploads
    volumes:
      - ./web_app:/app        
      - ./tests:/app/tests      
      - shared-audio:/data/uploads
    depends_on:
      - mongodb

  ml-client:
    build: ./machine_learning_client   
    container_name: emotion_ml
    command: ["python", "ml_client.py"]
    environment:
      - MONGO_URI=mongodb://mongodb:27017/emotiondb
      - AUDIO_DIR=/data/uploads
    volumes:
      - ./machine_learning_client:/app
      - shared-audio:/data/uploads
    depends_on:
      - mongodb

volumes:
  mongo_data:
  shared-audio:
